# Generated by Django 4.0.3 on 2022-03-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.endereco'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
